<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Dashboard Template for Bootstrap::Login</title>

        <link href="assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <script src="assets/plugins/jquery/jquery.js"></script>
        <script src="assets/plugins/bootstrap/js/bootstrap.js"></script>
        <style>
            .form-signin
            {
                max-width: 330px;
                padding: 15px;
                margin: 0 auto;
            }
            .account-wall
            {
                margin-top: 20px;
                padding: 40px 0px 0px 0px;
                background-color: #f7f7f7;
                -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            }
            .login-title
            {
                color: #555;
                font-size: 18px;
                font-weight: 400;
                display: block;
            }
            .profile-img
            {
                width: 96px;
                height: 96px;
                margin: 0 auto 10px;
                display: block;
                -moz-border-radius: 50%;
                -webkit-border-radius: 50%;
                border-radius: 50%;
            }
            .bg-danger, .bg-success {
                padding: 8px;
            }
            #groupfalso{
                height: 0.0001em;
                overflow: hidden;
                margin: 0;
            }
        </style>
        <script>
            $(function () {
                try {
                    $.ajaxSetup({
                        type: "POST"
                        , async: true
                        , dataType: "json"
                        , contentType: "application/x-www-form-urlencoded"
                        , timeout: 300000
                        , error: function ( ) {
                        }
                        , beforeSend: function ( ) {
                        }
                    });

                    $("#inputUsuario").on("keypress", function (event) {
                        if (event.keyCode == 13) {
                            $("#inputPassword").focus();
                        }
                    });

                    $("#inputPassword").on("keypress", function (event) {
                        if (event.keyCode == 13) {
                            $("#submitEntrar").click();
                        }
                    });

                    $("#submitEntrar").on("click", function (event) {
                        try {
                            $("#groupRespuesta").html("");
                            $.post("Autenticacion/autenticarUsuario.data", {
                                cuenta: $("#inputCuenta").val(),
                                password: $("#inputPassword").val()
                            }, function (respuesta) {
                                if (respuesta.status2) {
                                    var pseudoclass = 'bg-danger text-danger text-center';
                                    if (respuesta.autenticacion.autorizado) {
                                        pseudoclass = 'bg-success text-success text-center';
                                        setTimeout(function () {
                                            location.href = "./";
                                        }, 1000);
                                    }
                                    $("#groupRespuesta").html('<div class="col-md-12"><p class="' + pseudoclass + '">' + respuesta.autenticacion.respuesta + '</p></div>');
                                } else {
                                    $("#groupRespuesta").html('<div class="col-md-12"><p class="bg-warning text-warning p-10">' + respuesta.message + '</p></div>');
                                }
                            }, "json");
                        } catch (er) {
                            console.error(er);
                        }
                    });
                } catch (er) {
                    console.error(er);
                }

            });
        </script>
    </head>
    <body>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <h1 class="text-center login-title">Autenticar para continuar</h1>

                    <div class="account-wall">
                        <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                             alt="">

                        <form name="formLogin" id="formLogin" method="POST" class="form-signin margin-bottom-0 form-horizontal" 
                              onsubmit="javascript: return false">
                            <div id="groupfalso" class="form-group">
                                <div class="col-md-12">
                                    <input id="inputusuariofalso" name="inputusuariofalso" type="text" class="form-control input-md">
                                    <input id="inputpasswordfalso" name="inputpasswordfalso" type="password" class="form-control input-md">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="inputCuenta">Usuario</label>  
                                <div class="col-md-8">
                                    <input id="inputCuenta" name="inputCuenta" type="text" placeholder="Usuario" class="form-control input-md" maxlength="20" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="inputPassword">Password</label>
                                <div class="col-md-8">
                                    <input id="inputPassword" name="inputPassword" type="password" placeholder="Password" class="form-control input-md" maxlength="20" />
                                </div>
                            </div>

                            <div id="groupRespuesta" class="form-group">
                                <!--
                                <div class="col-md-12">
                                    <p class="bg-danger text-danger text-center">Usuario no encontrado.</p>
                                </div>
                                -->
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <button name="submitEntrar" id="submitEntrar" class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
                                </div>
                            </div>

                            <!--
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="checkbox">
                                        <label for="checkboxes-0">
                                            <input type="checkbox" name="checkboxes" id="checkboxes-0" value="1">
                                            Mantener sesion iniciada
                                        </label>
                                    </div>
                                </div>
                            </div>
                            -->
                        </form>
                    </div>

                    <!--
                    <div class="account-wall">

                    </div>
                    -->
                </div>

            </div>
        </div>

    </body>
</html>
